### ISSUE TITLE
Add LICENSE, DCO and Contributing documents

### ISSUE THREAD

**Issue by miguelsorianod** [bf2fc6cc711aee1a0c2a/ffm-fleet-manager-go-template#26]
See https://issues.redhat.com/browse/MGDSTRM-7442

**Comment by machi1990** [comment]
The contributing guide is there already https://github.com/bf2fc6cc711aee1a0c2a/ffm-fleet-manager-go-template/blob/main/CONTRIBUTING.md. It may need some updates.
